version: "3"

services:
  zion:
    build: ./zion
    container_name: zion
    hostname: zion
    networks:
      matrix:
        ipv4_address: 10.0.0.4
    cap_add:
      - NET_ADMIN
    ports:
      - "2222:22"
      - "80:80"
    restart: always
    volumes:
      - ./zion/zion.sh:/zion.sh
#    command: [ "/bin/sh", "/zion.sh" ]

  neo:
    build: ./neo
    container_name: neo
    hostname: neo
    networks:
      matrix:
        ipv4_address: 10.0.0.2
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - ./neo/neo.sh:/neo.sh
      - ./neo/rsyslog.conf:/etc/rsyslog.conf
#    command: ["/bin/sh", "/neo.sh"]

  smith:
    build: ./smith
    container_name: smith
    hostname: smith
    networks:
      matrix:
        ipv4_address: 10.0.0.3
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - ./smith/smith.sh:/smith.sh
#    command: [ "/bin/sh", "/smith.sh" ]

networks:
  matrix:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24